name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: ./MyMoneyApp
        run: npm install

      - name: Capacitor Sync
        working-directory: ./MyMoneyApp
        # استعملنا sync عوض copy باش يتقاد الـ Gradle أوتوماتيكياً
        run: npx @capacitor/cli sync

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build with Gradle
        working-directory: ./MyMoneyApp/android
        run: |
          chmod +x gradlew
          # زدنا هاد السطر باش يتفادى المشاكل ديال التضارب فـ Versions
          ./gradlew assembleDebug --stacktrace
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-money-app-apk
          path: MyMoneyApp/android/app/build/outputs/apk/debug/app-debug.apk
